### ISSUE TITLE
Getting Error in Ventos compilation

### ISSUE THREAD

**Issue by anika0625** [ManiAm/VENTOS_Public#4]
I am facing one issue during the compilation of ventos project.
 
Details of error are as follows:
 SumoServer.cc:39:27: error: ‘simulation’ was not declared in this scope
 cModule *module = simulation.getSystemModule()->getSubmodule("SumoBinary");
  
Request you to please provide the solution for it.
 
I have another query, Can I use Ventos on two different laptops and if yes than please provide the solution for that also or if you have any documentation regarding that so please share it with me.

**Comment by ManiAm** [comment]
> I am facing one issue during the compilation of ventos project.
Details of error are as follows:
SumoServer.cc:39:27: error: ‘simulation’ was not declared in this scope
cModule *module = simulation.getSystemModule()->getSubmodule("SumoBinary");

Are you using omnet 5? The version of the code we have in this repository only supports omnet 4.6.

https://omnetpp.org/component/jdownloads/category/32-release-older-versions?Itemid=-1


> I have another query, Can I use Ventos on two different laptops and if yes than please provide the solution for that

Can you explain more on what do you mean by using VENTOS on two laptops?

> also or if you have any documentation regarding that so please share it with me.

We do not have any documentation for VENTOS for now. But we are planning to write one in the near future.

**Comment by anika0625** [comment]
We want to run the Ventos on linux machine. The link you mention to download the omnet source code have the omnet 4.6 version for windows. Will it is suitable for linux as well???

My requirement is that I want to run Ventos on two different machines and both can be able to communicate with each other.

**Comment by ManiAm** [comment]
We only support Linux for now. 

The first link downloads the omnet version for linux.

**Comment by anika0625** [comment]
Hi

Thank you, for the help.

My query is whether I can run Ventos simulator on a distributed system, means  I want to run Ventos on two different machines and both can be able to communicate with each other. Please provide solution for it.

**Comment by ManiAm** [comment]
By default instances of VENTOS work independently from each other. You can add your desired functionality into the code.

**Comment by anika0625** [comment]
Hi

Thank you for clearing my doubts and for your support.

Thanks and Regards
Anika Gupta

**Comment by rafeemusabbir** [comment]
Hi
I am one of the PhD student of Dr. Michael. I have a query. How do you Install the VENTOS in Ubuntu 16.04.01 and also with OMNET 5.0. 


Thanks in Advance. 
Best,
Rafee

**Comment by ManiAm** [comment]
@rafeemusabbir : Hi rafee, can you post your question in a new issue. The current issue is closed.

Thanks!
